# actionlint configuration
# https://github.com/rhysd/actionlint/blob/main/docs/config.md

self-hosted-runner:
  labels: []

config-variables: []

# Ignore shellcheck info-level warnings (SC2086 unquoted variables)
# These are intentional in shell scripts that use glob patterns
